name: CI

on:
  push:
    branches: 
      - 'feature-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Build
      run:  docker build -t tech-trend-emporium ./TechTrendEmporium/TechTrendEmporium/
            # echo "Building the app"

  test:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Test
      # run: docker run tech-trend-emporium
      run: |
        echo "Testing the app" 
  
  release:

    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./TechTrendEmporium/TechTrendEmporium/
          push: true
          tags: tech-trend-emporium:${{ github.sha }}

    # - name: Tag
    #   run: |
    #     docker tag tech-trend-emporium tech-trend-emporium:${{ github.sha }}

    # - name: Login to DockerHub
    #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # - name: Code
    #   uses: actions/checkout@v3

    # - name: Build
    #   run:  docker build --tag tech-trend-emporium:${{ github.sha }} ./TechTrendEmporium/TechTrendEmporium/

    # - name: Tag
    #   run: docker tag tech-trend-emporium tech-trend-emporium:1.0.0

    # - name: Push
    #   run: docker push backendchallenge2024/tech-trend-emporium:${{ github.sha }}

      # run: |
      #   docker build -t tech-trend-emporium ./TechTrendEmporium/TechTrendEmporium/
      #   docker tag tech-trend-emporium tech-trend-emporium:${{ github.sha }}
      #   docker push tech-trend-emporium:${{ github.sha }}
