name: CI

on:
  push:
    branches: 
      - 'feature-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Build
      run: docker build -t backendchallenge2024/tech-trend-emporium:${{ github.sha }} ./TechTrendEmporium/TechTrendEmporium/
  
  test:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Test
      run: |
        echo "Testing the app" 
  
  release:

    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Code
      uses: actions/checkout@v3

    - name: Tag
      run: docker tag backendchallenge2024/tech-trend-emporium:${{ github.sha }} backendchallenge2024/tech-trend-emporium:latest

    - name: Push
      run: docker push backendchallenge2024/tech-trend-emporium:${{ github.sha }}
